---
# Base Execution Environment available in all environments
# Using _all suffix for wildcard merging

controller_execution_environments_all:
  - name: Default Execution Environment
    description: Base EE with core Ansible collections
    image: "{{ aap_hostname }}/custom-ee:{{ tag }}"
    pull: always
...
