---
# Production Environment Inventory Hosts
# Using _prod suffix for wildcard merging

controller_hosts_all:
  - name: localhost
    description: Local execution
    inventory: Production Localhost
    variables:
      ansible_connection: local
      ansible_python_interpreter: /usr/bin/python3
...
