---
controller_inventory_sources_all:
  - name: platform_aap_{{ env }}_source
    organization: platform
    source: scm
    source_project: plat_aap_inv_config
    source_path: inventory/inventory_{{ env }}.yml
    inventory: "plat_aap_{{ env }}"
    credential: ""
    overwrite: true
    overwrite_vars: true
    update_cache_timeout: 0

...
