---
# Execution Environment
controller_execution_environments_plat_backup_database:
  - name: "plat_database_backup_ee_{{ jt_plat_backup_database | default(ee_image) }}"
    description: "Platform database backup execution environment"
    image: "quay.io/myorg/custom-ee:{{ jt_plat_backup_database | default(ee_image) }}"
    pull: "missing"
    credential: "plat_registry_svc_builder_quay_io"

# Project
controller_projects_plat_backup_database:
  - name: "plat_database_backup_playbooks"
    description: "Platform database backup playbooks"
    scm_type: git
    scm_url: "https://github.com/djdanielsson/rh1-automation-playbooks.git"
    scm_branch: "{{ jt_plat_backup_database | default(scm_branch) }}"
    scm_clean: true
    scm_delete_on_update: true
    scm_update_on_launch: false
    credential: "plat_scm_djdanielsson_github"
    timeout: 0
    organization: "platform"

# Job Template
controller_templates_plat_backup_database:
  - name: "plat_backup_database_{{ env }}"
    description: "Backup PostgreSQL database on {{ env }} servers"
    job_type: "run"
    inventory: "plat_databases_{{ env }}"
    project: "plat_database_backup_playbooks"
    playbook: "playbooks/backup-database.yml"
    execution_environment: "plat_database_backup_ee_{{ jt_plat_backup_database | default(ee_image) }}"
    credentials:
      - "plat_machine_svc_ansible_linux"
    organization: "platform"
    ask_variables_on_launch: true
    extra_vars:
      database_name: "appdb"
      database_user: "app_user"
      database_port: 5432
      database_backup_firewall: true
...
