---
# Dev Environment Projects (SCM Connections)
# All using wildcard suffixes for consistent merging

controller_projects_dev:
  - name: Example Ansible Collection
    description: Example automation collection
    organization: Default
    scm_type: git
    scm_url: https://github.com/djdanielsson/rh1-custom-collection.git
    scm_branch: main
    scm_update_on_launch: true
    scm_delete_on_update: true
    credential: Dev GitHub Token
    default_environment: Web EE (Dev)...
...
