---
# This token is used to synchronise certifified and validated collections from console.redhat.com.
# To generate an AH token, go to the url: https://console.redhat.com/ansible/automation-hub/token and click on
# "Load Token" in the "Offline token" chapter.
console_token: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  61616338353735316438373334633230633837316163386535323133303134663663313662393631
  6136376138626462343036386265366239336236653763630a383533663166303539623938356435
  63663731343931613133396635616139343766613966313430643931666365653037353635623762
  6336623633313432370a396636313365373161616161623135373732636464656432666133646465
  37666639666265373363343665353634373664313338386330636162393531376161313637643835
  37336330646639313338653834646366373233316166326636306465343631393564386335343666
  62303435653638613565356466333437353462633938623236353261643233326332306331613164
  61353365313935646438373666666237386338323039343466383665376166353263636463663964
  66323166643763396131326130633437326235663332633930393130313535663132366534356535
  63383364326632363234343265666662616138646530633162643232616338383033633363623035
  62646531373861333734343833326564306562333266346339303439643862633936373962663261
  36313938643835326139653530623233643166386135356133363131333336643933316564383062
  38396232656164363162346639643035323632383563323932613536626165326435663033303537
  66373639333231303565386264633462313639383035333933356262653365366562653935643531
  66633561363638363732386438626431653638666563303033306235343331363365306361383030
  64623732393361376266313566626635393161626631623265386634646133633930346565393363
  66666539643637623861633939356534366432643032383832303336386164363336346134316137
  62313261663235633063353738333538316230626564323233613934333061636335313163323431
  38633039316536316164623566636537336534633434623839643264363032356666353064313539
  61373237653164323738313532613437643631333537376465333734316633333034353630356537
  30643435663466346534313736613234376330353530313336646135376561336565326534353338
  31323763303862343166643532386463343331386238323436636136623064323338316263626438
  63643233306534323537303932633535383663376330323034623630386532363935393632393132
  37373634626261363163646538636537373530653363306630636138363636316431623634353165
  66353136373835643830346237623039636138646437383363323639376261383165376262323034
  38393431663634653765366564643731646532613463356336623731393164633162316532363065
  64313962636230623136303461323633313636366435366439643836353233383736383563633365
  64336561663039303636636366356266326366373834323463386362343934363162313066643665
  37343338323062666531616534326365653737636561396265336366336231333038633434363333
  39393234376162633862636530323636613962383064653065393430393735333263666533373661
  39623739656632626137316265636261316162303231663163373366333634333630386462396230
  39623334663461373337343335663966656633353862373337616334333337303134623737306261
  66343761386635643661666438333063663063303762623230363135383963323139333834643135
  30656561633363336534333535663663366464393164633136343564626164363631376631613438
  33623766386234613361636134626335303736346564643333396335306430353564336433656365
  39643130313431396461396365326239343533396566613333386564616432303936636331653837
  32646463386531386530613838346439333636653966643266396464656431643636353336396634
  61646461323532316266636338383536313032306631636435383535643461623563313132396131
  34306662376537373033343831636333633862616631316363373431636531633466306131316333
  64313562376239393938653066323834643265363632613336336561663064393132313236393936
  32333161333161373739666133636130343361626637373935336663643966363234386131323962
  32613265326530303865636137613530376464376534656164396665386463363563626265623839
  376361393333303535323838303564323564

# The password to decrypt this vault
vault_pass: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  61323739316136653164376233336431326638356435343131363835643436623632383766623730
  6131353062326665366239653530376137363565376462630a623265623636623461303138646566
  31643961626632643130656165336462643562613336643566343235353265346261663265613835
  3736373837616239360a313633633664326664323931366165666461366634633062313131656364
  35373034653563393761613533366633393735306563643161363463613934393132336534643662
  39616662313930366535383033363131636131303935653038366530626634306130663533326139
  33656633356132383336656535636464613637363537393038653433376163366532306533356637
  33366536366465303637303265323063633033363736666137383463396439333331633238343661
  31313139346234663834323364303134336139663237326532356337333066383039663564656538
  32363361313133663965353964363763396131663836313865306332373833366137333161633738
  363433633364623533383739623965336130

aap_pass: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  36666137356361336632643431313764393862373463383631326639333165346336353062346562
  6639393363663033613664663662363531343137373136340a666266393434376566303565636439
  38333164653565376235396633343333613461643034373064383032386639363665616161646664
  3039366562343330370a656237373362363037333032343334646332356562396163366465656134
  61643838313561313731373335306335626362623732623430616434356436626366666534343861
  3933343238363163646561633038313730613433643735653731

hub_token: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  33323535386164336139383736386536656439323566636333613134356436623837626534363337
  6635326430343637653238383863616337623537333134320a363235663064653961613063386165
  64363762346564656336346331663531303964326434613461383966653835656463353839376231
  3832323535303365310a303438396633363736333634386132376265313466383735396331646261
  64333964613061336236366435666261393038373734626536656336633235326265343737313062
  3665343239663335363435663731313535303763653837623936
...
