apiVersion: aap.ansible.com/v1alpha1
kind: AnsibleAutomationPlatform
metadata:
  name: tekton-testing
spec:
  api:
    log_level: INFO
    replicas: 1
  hub:
    file_storage_access_mode: ReadWriteOnce
  image_pull_policy: Always
  ingress_type: Route
  no_log: false
  redis_mode: standalone
  route_tls_termination_mechanism: Edge
  service_type: ClusterIP
  eda:
    disabled: true